
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuoteServiceImplService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8888/quotes?wsdl")
public class QuoteServiceImplService
    extends Service
{

    private final static URL QUOTESERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUOTESERVICEIMPLSERVICE_EXCEPTION;
    private final static QName QUOTESERVICEIMPLSERVICE_QNAME = new QName("http://service/", "QuoteServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/quotes?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUOTESERVICEIMPLSERVICE_WSDL_LOCATION = url;
        QUOTESERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public QuoteServiceImplService() {
        super(__getWsdlLocation(), QUOTESERVICEIMPLSERVICE_QNAME);
    }

    public QuoteServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUOTESERVICEIMPLSERVICE_QNAME, features);
    }

    public QuoteServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, QUOTESERVICEIMPLSERVICE_QNAME);
    }

    public QuoteServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUOTESERVICEIMPLSERVICE_QNAME, features);
    }

    public QuoteServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuoteServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuoteService
     */
    @WebEndpoint(name = "QuoteServiceImplPort")
    public QuoteService getQuoteServiceImplPort() {
        return super.getPort(new QName("http://service/", "QuoteServiceImplPort"), QuoteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuoteService
     */
    @WebEndpoint(name = "QuoteServiceImplPort")
    public QuoteService getQuoteServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "QuoteServiceImplPort"), QuoteService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUOTESERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw QUOTESERVICEIMPLSERVICE_EXCEPTION;
        }
        return QUOTESERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
